spring:
  config:
    import: "aws-parameterstore:/prod/damm/"
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: 6379

logging:
  level:
    io.awspring.cloud: DEBUG